name: joel-the-messenger
favicon: null
layout_spectrum: 0.64587
typography_spectrum: 0.6635743214283139
title: Houston Recording Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbbbbb'
    - '#ffffff'
    - '#525252'
    - '#f3fc37'
    - '#f6952f'
  brandStrength: 0.25
  lightness: 0.12984220404177904
  saturation: 0.7697326752822846
  rhythmicContrast: 0.7887123303953558
purpose: []
