name: joel-the-messenger
favicon: null
layout_spectrum: 0.86862
typography_spectrum: 0.6635743214283139
title: Joel the Messenger - Houston Singer/Songwriter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbbbbb'
    - '#ffffff'
    - '#525252'
    - '#f3fc37'
    - '#f6952f'
  brandStrength: 0.25
  lightness: 0.12984220404177904
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
